### ISSUE TITLE
readme file does not reference tasks by correct name.

### ISSUE THREAD

**Issue by stealthrabbi** [SimonScholz/report-aggregator#1]
I see:

SpotBugs tasks
--------------
aggregateSpotBugsFiles - Aggregates all SpotBugs xml files into one SpotBugsAggregated.xml file
generateAggregatedReport - Generate HTML report from Aggregated SpotBugs xml files

**Comment by SimonScholz** [comment]
Fixed with my latest commit.
Please reopen if you face further issues
